
package com.calc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorPortType", targetNamespace = "http://calc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorPortType {


    /**
     * 
     * @param num1
     * @param num2
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Add", action = "http://calc.com/Add")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "Add", targetNamespace = "http://calc.com/", className = "com.calc.Add")
    @ResponseWrapper(localName = "AddResponse", targetNamespace = "http://calc.com/", className = "com.calc.AddResponse")
    public int add(
        @WebParam(name = "num1", targetNamespace = "")
        int num1,
        @WebParam(name = "num2", targetNamespace = "")
        int num2);

}
